version: '2'
services:
  auth-balancer:
    image: rancher/lb-service-haproxy:v0.7.5
    ports:
    - 10000:10000/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'
  geoq-microsoa-auth:
    image: djimenezgarcia/test:geoq-microsoa-auth
    stdin_open: true
    volumes:
    - /GeoQ/geoq-core:/var/lib/tomcat7/webapps/GeoQ
    - /GeoQ:/GeoQ
    tty: true
    labels:
      io.rancher.container.pull_image: always
